const Discord = require("discord.js"); // puxando a livraria discord.js

exports.run = async (doky, message, args) => { 
  return;
}

exports.help = {
    name: 'addmoney',
  aliases: ['moneyadd', 
            'vip', 
            'vip-info', 
            'info-vip', 
            'loja', 
            'loja-info', 
            'info-loja',
            'semanal', 
            'weekly',
            'starcoins',
            'daily',
            'diario',
            'demissão',
            'demissao',
            'emprego',
            'trabalho', 
            'trabalhos', 
            'empregos',
            'loja-cores',
            'coresloja', 
            'loja-cor',
            'loja-vip', 
            'viploja',
            'wallpapers-loja',
            'loja-wallpaper',
            'loja-wallpapers',
            'pagar', 
            'enviar',
            'pay',
            'perfil',
            'profile',
            'removemoney',
            'moneyremove',
            'resetmoney',
            'moneyreset',
            'resetvip',
            'vipreset',
            'saldo',
            'money', 
            'bal', 
            'balance',
            'bioset',
            'bio',
            'setbio',
            'setcor',
            'colorset',
            'corset',
            'setcolor',
            'setvip',
            'vipset',
            'setwallpaper',
            'wallpaperset',
            'vender',
            'sell',
            'trabalhar',
            'work', 
            'trabalho',
            'play',
            'e',
            'resetbio',
            'bioreset',
            'bag',
            'inventario'
           ]
}